meamr_teleop_node:  # Node name
  ros__parameters:
    axis_linear.x: 1 # Left stick vertical axis
    scale_linear.x: 0.7

    axis_angular.yaw: 3 # Left stick horizontal axis
    scale_angular.yaw: 1.0
    
    enable_button: 4 # Left trigger button